// <auto-generated />
namespace MVCDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class acctyp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(acctyp));
        
        string IMigrationMetadata.Id
        {
            get { return "202102030850327_acctyp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
